#!/usr/bin/env bash
# setup.sh — Configure Claude Code to use DeepSeek API as backend
# Repository: https://github.com/xuechaow/cld_deep
#
# Usage:
#   ./setup.sh                        # Interactive, prompts for API key
#   ./setup.sh sk-your-api-key        # Non-interactive
#   ./setup.sh --uninstall            # Remove all configuration
#   ./setup.sh --shell fish           # Override shell auto-detection
#   ./setup.sh --no-test              # Skip API connectivity test
#   ./setup.sh --dry-run              # Show what would be done
#
# One-liner:
#   curl -fsSL https://raw.githubusercontent.com/xuechaow/cld_deep/main/setup.sh | bash -s -- YOUR_API_KEY

set -euo pipefail

# ── Configuration defaults (override via env vars before running) ─────
BASE_URL="${CLD_DEEP_BASE_URL:-https://api.deepseek.com/anthropic}"
SONNET_MODEL="${CLD_DEEP_SONNET_MODEL:-deepseek-v4-pro}"
OPUS_MODEL="${CLD_DEEP_OPUS_MODEL:-deepseek-v4-pro}"
HAIKU_MODEL="${CLD_DEEP_HAIKU_MODEL:-deepseek-v4-flash}"
SUBAGENT_MODEL="${CLD_DEEP_SUBAGENT_MODEL:-deepseek-v4-flash}"
EFFORT_LEVEL="${CLD_DEEP_EFFORT_LEVEL:-max}"

ENV_DIR="${HOME}/.deepseek-claude"
ENV_FILE="${ENV_DIR}/env"
ENV_FILE_FISH="${ENV_DIR}/env.fish"

# ── Terminal colors ───────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

error()   { echo -e "${RED}Error:${NC} $*" >&2; }
success() { echo -e "${GREEN}✓${NC} $*"; }
info()    { echo -e "${YELLOW}→${NC} $*"; }
step()    { echo -e "${BLUE}→${NC} $*"; }

# ── Usage ─────────────────────────────────────────────────────────────
usage() {
    cat <<EOF
${BOLD}DeepSeek + Claude Code Integration Setup${NC}

Configure Claude Code to use the DeepSeek API as its model backend.

${BOLD}Usage:${NC}
  setup.sh [OPTIONS] [API_KEY]

${BOLD}Options:${NC}
  -h, --help        Show this help message
  -u, --uninstall   Remove all configuration files and shell integration
  -s, --shell NAME  Specify shell (bash, zsh, fish). Auto-detected by default.
  -n, --no-test     Skip the API connectivity test after setup
  -d, --dry-run     Print what would be done without making changes
  -q, --quiet       Suppress informational output (errors still shown)

${BOLD}Examples:${NC}
  setup.sh                           # Interactive mode
  setup.sh sk-abc123def456           # Non-interactive with API key
  setup.sh --shell fish sk-...       # Force fish shell config
  setup.sh --uninstall               # Remove integration
  setup.sh --dry-run                 # Preview changes

${BOLD}Environment variable overrides:${NC}
  CLD_DEEP_BASE_URL          Default: ${BASE_URL}
  CLD_DEEP_SONNET_MODEL      Default: ${SONNET_MODEL}
  CLD_DEEP_OPUS_MODEL        Default: ${OPUS_MODEL}
  CLD_DEEP_HAIKU_MODEL       Default: ${HAIKU_MODEL}
  CLD_DEEP_SUBAGENT_MODEL    Default: ${SUBAGENT_MODEL}
  CLD_DEEP_EFFORT_LEVEL      Default: ${EFFORT_LEVEL}

${BOLD}Supported shells:${NC} bash, zsh, fish
EOF
    exit 0
}

# ── Shell detection ───────────────────────────────────────────────────
detect_shell() {
    # Respect explicit override
    if [[ -n "${ARG_SHELL:-}" ]]; then
        echo "$ARG_SHELL"
        return
    fi
    local name
    name=$(basename "${SHELL:-/bin/bash}")
    echo "$name"
}

detect_shell_config() {
    local shell_name="$1"
    case "$shell_name" in
        zsh)  echo "${ZDOTDIR:-$HOME}/.zshrc" ;;
        bash)
            if [[ "$(uname)" == "Darwin" ]]; then
                # macOS Terminal.app opens login shells → .bash_profile
                echo "$HOME/.bash_profile"
            else
                echo "$HOME/.bashrc"
            fi
            ;;
        fish) echo "$HOME/.config/fish/config.fish" ;;
        *)
            error "Unsupported shell: ${shell_name}. Use --shell to specify bash, zsh, or fish."
            exit 1
            ;;
    esac
}

# ── API key validation ────────────────────────────────────────────────
validate_api_key() {
    local key="$1"
    if [[ -z "$key" ]]; then
        error "API key cannot be empty."
        return 1
    fi
    if [[ ! "$key" =~ ^sk-[A-Za-z0-9]+$ ]]; then
        error "API key should start with 'sk-' and contain only alphanumeric characters."
        return 1
    fi
    return 0
}

# ── Write env file (POSIX export syntax for bash/zsh) ─────────────────
write_posix_env() {
    local key="$1"
    cat > "$ENV_FILE" <<ENVEOF
# DeepSeek + Claude Code integration
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Repository: https://github.com/xuechaow/cld_deep

export ANTHROPIC_BASE_URL="${BASE_URL}"
export ANTHROPIC_AUTH_TOKEN="${key}"
export ANTHROPIC_DEFAULT_SONNET_MODEL="${SONNET_MODEL}"
export ANTHROPIC_DEFAULT_OPUS_MODEL="${OPUS_MODEL}"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="${HAIKU_MODEL}"
export CLAUDE_CODE_SUBAGENT_MODEL="${SUBAGENT_MODEL}"
export CLAUDE_CODE_EFFORT_LEVEL="${EFFORT_LEVEL}"
ENVEOF
    chmod 600 "$ENV_FILE"
}

# ── Write env file (fish set -gx syntax) ──────────────────────────────
write_fish_env() {
    local key="$1"
    cat > "$ENV_FILE_FISH" <<ENVEOF
# DeepSeek + Claude Code integration
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Repository: https://github.com/xuechaow/cld_deep

set -gx ANTHROPIC_BASE_URL "${BASE_URL}"
set -gx ANTHROPIC_AUTH_TOKEN "${key}"
set -gx ANTHROPIC_DEFAULT_SONNET_MODEL "${SONNET_MODEL}"
set -gx ANTHROPIC_DEFAULT_OPUS_MODEL "${OPUS_MODEL}"
set -gx ANTHROPIC_DEFAULT_HAIKU_MODEL "${HAIKU_MODEL}"
set -gx CLAUDE_CODE_SUBAGENT_MODEL "${SUBAGENT_MODEL}"
set -gx CLAUDE_CODE_EFFORT_LEVEL "${EFFORT_LEVEL}"
ENVEOF
    chmod 600 "$ENV_FILE_FISH"
}

# ── Add source line to shell config ───────────────────────────────────
add_source_line() {
    local config_file="$1"
    local shell_name="$2"
    local source_line
    local marker_start="# >>> DeepSeek Claude integration >>>"
    local marker_end="# <<< DeepSeek Claude integration <<<"

    # Determine source line based on shell
    case "$shell_name" in
        fish)
            source_line="source ${ENV_FILE_FISH}"
            ;;
        *)
            source_line="[ -f ${ENV_FILE} ] && source ${ENV_FILE}"
            ;;
    esac

    # Remove any existing integration block
    remove_source_block "$config_file"

    # Ensure file exists
    mkdir -p "$(dirname "$config_file")"
    touch "$config_file"

    # Add trailing newline if needed
    if [[ -s "$config_file" ]] && [[ "$(tail -c 1 "$config_file")" != $'\n' ]]; then
        echo "" >> "$config_file"
    fi

    {
        echo ""
        echo "$marker_start"
        echo "$source_line"
        echo "$marker_end"
    } >> "$config_file"
}

# ── Remove integration block from shell config ────────────────────────
remove_source_block() {
    local config_file="$1"
    local marker_start="# >>> DeepSeek Claude integration >>>"
    local marker_end="# <<< DeepSeek Claude integration <<<"

    if [[ ! -f "$config_file" ]]; then
        return 0
    fi

    # macOS sed vs GNU sed compat
    if [[ "$(uname)" == "Darwin" ]]; then
        sed -i '' "/^${marker_start//\//\\/}/,/^${marker_end//\//\\/}/d" "$config_file" 2>/dev/null || true
    else
        sed -i "/^${marker_start//\//\\/}/,/^${marker_end//\//\\/}/d" "$config_file" 2>/dev/null || true
    fi
}

# ── Test API connectivity ─────────────────────────────────────────────
test_api() {
    local key="$1"
    local url="${BASE_URL}/v1/messages"

    step "Testing connection to DeepSeek API (${url})..."

    local response http_code
    response=$(curl -s -w "\n%{http_code}" -m 20 -X POST "$url" \
        -H "Content-Type: application/json" \
        -H "x-api-key: ${key}" \
        -H "anthropic-version: 2023-06-01" \
        -d "{\"model\":\"${SONNET_MODEL}\",\"max_tokens\":8,\"messages\":[{\"role\":\"user\",\"content\":\"say OK\"}]}" 2>&1) || {
        error "Could not reach the API. Check your network and the BASE_URL."
        return 1
    }

    http_code=$(echo "$response" | tail -1)
    local body
    body=$(echo "$response" | sed '$d')

    if [[ "$http_code" == "200" ]] && echo "$body" | grep -q '"id":'; then
        success "API connection verified (HTTP ${http_code})."
        return 0
    else
        error "API test returned HTTP ${http_code}."
        echo "Response: $(echo "$body" | head -c 500)" >&2
        return 1
    fi
}

# ── Export to current shell session ───────────────────────────────────
export_to_current_shell() {
    local key="$1"
    local shell_name="$2"

    step "Exporting variables to current shell..."

    if [[ "$shell_name" == "fish" ]]; then
        # We can't export directly from bash into a fish parent process.
        # Instead we print commands the user can evaluate.
        cat <<FISHCMD

  Your shell is ${BOLD}fish${NC}. Environment variables cannot be set in the
  current session from a bash script. Run this command manually:

    ${GREEN}source ${ENV_FILE_FISH}${NC}

  Or open a new terminal — the variables load automatically.
FISHCMD
        return 0
    fi

    export ANTHROPIC_BASE_URL="${BASE_URL}"
    export ANTHROPIC_AUTH_TOKEN="${key}"
    export ANTHROPIC_DEFAULT_SONNET_MODEL="${SONNET_MODEL}"
    export ANTHROPIC_DEFAULT_OPUS_MODEL="${OPUS_MODEL}"
    export ANTHROPIC_DEFAULT_HAIKU_MODEL="${HAIKU_MODEL}"
    export CLAUDE_CODE_SUBAGENT_MODEL="${SUBAGENT_MODEL}"
    export CLAUDE_CODE_EFFORT_LEVEL="${EFFORT_LEVEL}"
    success "Variables exported to current ${shell_name} session."
}

# ── Install ───────────────────────────────────────────────────────────
do_install() {
    local key="$1"
    local shell_name="$2"
    local config_file="$3"

    echo ""
    echo -e "${BOLD}${BLUE}╔══════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}${BLUE}║  DeepSeek + Claude Code Integration Setup    ║${NC}"
    echo -e "${BOLD}${BLUE}╚══════════════════════════════════════════════╝${NC}"
    echo ""

    validate_api_key "$key" || exit 1

    info "Shell:       ${shell_name}"
    info "Config file: ${config_file}"
    info "Env dir:     ${ENV_DIR}"
    echo ""

    if [[ "${ARG_DRY_RUN:-false}" == "true" ]]; then
        echo -e "${YELLOW}[DRY RUN]${NC} Would create ${ENV_FILE} with API key and model config."
        if [[ "$shell_name" == "fish" ]]; then
            echo -e "${YELLOW}[DRY RUN]${NC} Would also create ${ENV_FILE_FISH} with fish syntax."
        fi
        echo -e "${YELLOW}[DRY RUN]${NC} Would add source line to ${config_file}."
        echo -e "${YELLOW}[DRY RUN]${NC} Would test API connectivity."
        return 0
    fi

    # Create env directory
    mkdir -p "$ENV_DIR"
    chmod 700 "$ENV_DIR"

    # Write env file(s)
    if [[ "$shell_name" == "fish" ]]; then
        write_fish_env "$key"
        success "Created ${ENV_FILE_FISH}"
    fi
    write_posix_env "$key"
    success "Created ${ENV_FILE}"

    # Add source line to shell config
    add_source_line "$config_file" "$shell_name"
    success "Updated ${config_file}"

    # Export to current session
    export_to_current_shell "$key" "$shell_name"

    # Test API
    echo ""
    if [[ "${ARG_NO_TEST:-false}" != "true" ]]; then
        if test_api "$key"; then
            echo ""
            echo -e "${GREEN}${BOLD}🎉 Setup complete!${NC}"
            echo ""
            echo -e "  Run:  ${BOLD}claude --bare${NC}"
            echo ""
            echo "  For new terminals, the config loads automatically."
            echo "  To verify:  echo \$ANTHROPIC_BASE_URL"
        else
            echo ""
            echo -e "${YELLOW}Configuration written, but the API test failed.${NC}"
            echo "  Check your API key and network, then try again:"
            echo "  ${BOLD}source ${ENV_FILE}${NC}"
            exit 1
        fi
    else
        echo -e "${GREEN}${BOLD}✓ Setup complete (API test skipped).${NC}"
        echo ""
        echo -e "  Run:  ${BOLD}claude --bare${NC}"
    fi
}

# ── Uninstall ─────────────────────────────────────────────────────────
do_uninstall() {
    local shell_name="$1"
    local config_file="$2"

    echo ""
    echo -e "${BOLD}${YELLOW}DeepSeek + Claude Code — Uninstall${NC}"
    echo ""

    if [[ "${ARG_DRY_RUN:-false}" == "true" ]]; then
        echo -e "${YELLOW}[DRY RUN]${NC} Would remove integration block from ${config_file}."
        echo -e "${YELLOW}[DRY RUN]${NC} Would delete ${ENV_DIR}/"
        return 0
    fi

    # Remove source block from shell config
    if [[ -f "$config_file" ]]; then
        remove_source_block "$config_file"
        success "Removed integration from ${config_file}"
    fi

    # Remove env files
    if [[ -d "$ENV_DIR" ]]; then
        rm -rf "$ENV_DIR"
        success "Removed ${ENV_DIR}/"
    fi

    echo ""
    echo -e "${GREEN}Uninstall complete.${NC}"
    echo ""
    echo "  The following variables are ${BOLD}still set${NC} in this terminal session:"
    echo "    ANTHROPIC_BASE_URL, ANTHROPIC_AUTH_TOKEN, model vars"
    echo "  They will be gone when you open a new terminal."
    echo ""
    echo "  To clear them now:"
    echo "    unset ANTHROPIC_BASE_URL ANTHROPIC_AUTH_TOKEN ANTHROPIC_DEFAULT_SONNET_MODEL"
    echo "    unset ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_HAIKU_MODEL"
    echo "    unset CLAUDE_CODE_SUBAGENT_MODEL CLAUDE_CODE_EFFORT_LEVEL"
    echo ""
}

# ── Main ──────────────────────────────────────────────────────────────
main() {
    local ARG_SHELL=""
    local ARG_UNINSTALL=false
    local ARG_NO_TEST=false
    local ARG_DRY_RUN=false
    local ARG_QUIET=false
    local API_KEY=""

    # Parse flags
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h|--help)     usage ;;
            -u|--uninstall) ARG_UNINSTALL=true; shift ;;
            -s|--shell)    ARG_SHELL="$2"; shift 2 ;;
            -n|--no-test)  ARG_NO_TEST=true; shift ;;
            -d|--dry-run)  ARG_DRY_RUN=true; shift ;;
            -q|--quiet)    ARG_QUIET=true; shift ;;
            --)            shift; break ;;
            -*)            error "Unknown option: $1"; usage; exit 1 ;;
            *)             API_KEY="$1"; shift; break ;;
        esac
    done

    # Remaining positional args
    if [[ -z "$API_KEY" ]] && [[ $# -gt 0 ]]; then
        API_KEY="$1"
    fi

    # Detect shell and config
    local shell_name config_file
    shell_name=$(detect_shell)
    config_file=$(detect_shell_config "$shell_name")

    if [[ "$ARG_QUIET" == "true" ]]; then
        success() { :; }
        info()    { :; }
        step()    { :; }
    fi

    # Dispatch
    if [[ "$ARG_UNINSTALL" == "true" ]]; then
        do_uninstall "$shell_name" "$config_file"
        return 0
    fi

    # If no API key provided, prompt interactively
    if [[ -z "$API_KEY" ]]; then
        echo -n "Enter your DeepSeek API key (starts with sk-): "
        read -r API_KEY
        echo ""
    fi

    do_install "$API_KEY" "$shell_name" "$config_file"
}

main "$@"
